on: [push, pull_request]

jobs:

  build:
    name: ${{ matrix.OS }}

    strategy:
      matrix:
        OS:
        - macos-13  # Intel
        - macos-14  # M1
        - ubuntu-24.04
        - ubuntu-22.04
      fail-fast: false
    runs-on: ${{ matrix.OS }}

    # NOTE: PWD = GITHUB_WORKSPACE = /home/runner/work/cl-repl/cl-repl = ~/work/cl-repl/cl-repl
    #       HOME = /home/runner

    steps:

    - uses: actions/checkout@v4

    - name: Install Roswell and SBCL (Ubuntu)
      if: startsWith(matrix.OS, 'ubuntu')
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
        ros install sbcl-bin

    - name: Dump lisp image (Ubuntu)
      if: startsWith(matrix.OS, 'ubuntu')
      run: |
        ros run -- \
             --load cl-repl.asd \
             --eval '(ql:quickload :cl-repl)' \
             --eval '(asdf:make :cl-repl)' \
             --quit

    - name: Install SBCL and quicklisp (macOS)
      if: startsWith(matrix.OS, 'macos')
      run: |
        brew install sbcl
        wget https://beta.quicklisp.org/quicklisp.lisp
        echo -ne '\n' | \
        sbcl --load quicklisp.lisp \
             --eval '(quicklisp-quickstart:install)' \
             --eval '(ql:add-to-init-file)' \
             --quit

    - name: Dump lisp image (macOS)
      if: startsWith(matrix.OS, 'macos')
      run: |
        sbcl --load cl-repl.asd \
             --eval '(ql:quickload :cl-repl)' \
             --eval '(asdf:make :cl-repl)' \
             --quit

    - name: Set release name
      run: echo "CL_REPL_BIN=cl-repl.${{ matrix.OS }}.$(uname -m).bin" >> $GITHUB_ENV

    - name: Rename lisp image
      run: mv cl-repl ${{ env.CL_REPL_BIN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.CL_REPL_BIN }}
        path: ${{ env.CL_REPL_BIN }}
        compression-level: 0

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: ${{ env.CL_REPL_BIN }}
